service: desktop-configuration-api
runtime: nodejs20
env: standard
env_variables:
  DBHOST: "34.67.143.103"
  DBNAME: "wiseape-client-hris"
  DBUSER: "nodeuser"
  DBPASSWORD: "RotiKeju98*"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "Wiseape Desktop"
  APPLICATION_TITLE : "Wiseape Desktop"
  APPLICATION_PORT : "8080"
  PROJECT : "huda-playground"

